### ISSUE TITLE
Merge error in efiloader/src/main.rs

### ISSUE THREAD

**Issue by mtnygard** [IsaacWoods/pebble#55]
https://github.com/IsaacWoods/pebble/blob/e0a9a24a62908ed120bef03dcd29f1109fb4fe73/kernel/efiloader/src/main.rs#L453-L454

Two versions of the fn declaration for `find_volume`. I'd submit a PR but I can't tell which one is correct.

**Comment by IsaacWoods** [comment]
Huh, looks like the removal of the first line got left out of [this commit](https://github.com/IsaacWoods/pebble/commit/1329c0b2273ea79f25886c468cb7cd8520832a9a) somehow.

Thanks for the report! This is fixed now.
